Updating the test workflows.

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -3,50 +3,27 @@ default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
 
 app:
   envs:
-  # An example secret param, define it (A_SECRET_PARAM) in .bitrise.secrets.yml
-  - A_SECRET_PARAM: $A_SECRET_PARAM
+  - SAMPLE_APP_REPOSITORY_URL: https://github.com/bitrise-samples/sample-apps-android-abi-split.git
+  - BRANCH: master
+  - GRADLEW_PATH: "./gradlew"
+
   # If you want to share this step into a StepLib
   - BITRISE_STEP_ID: zipalign-apk
-  - BITRISE_STEP_VERSION: "0.0.1"
+  - BITRISE_STEP_VERSION: "0.1.0"
   - BITRISE_STEP_GIT_CLONE_URL: https://github.com/MCeley/bitrise-step-zipalign-apk.git
   - MY_STEPLIB_REPO_FORK_GIT_URL: $MY_STEPLIB_REPO_FORK_GIT_URL
 
 workflows:
-  test:
+  audit_run:
+    before_run:
+    - audit-this-step
     steps:
-    - script:
-        inputs:
-        - content: |
-            #!/bin/bash
-            echo "Just an example 'secrets' print."
-            echo "The value of 'A_SECRET_PARAM' is: $A_SECRET_PARAM"
-    - change-workdir:
-        title: Switch working dir to test / _tmp dir
-        description: |-
-          To prevent step testing issues, like referencing relative
-          files with just './some-file' in the step's code, which would
-          work for testing the step from this directory directly
-          but would break if the step is included in another `bitrise.yml`.
-        run_if: true
-        inputs:
-        - path: ./_tmp
-        - is_create_path: true
-    - path::./:
-        title: Step Test
-        description: |-
-          The example input has a default value,
-          you can overwrite it if you want to, just like we did below,
-          but the step would use the default value specified in the `step.yml`
-          file if you would not specify another value.
-        run_if: true
-        inputs:
-        - example_step_input: Example Step Input's value
-    - script:
-        inputs:
-        - content: |
-            #!/bin/bash
-            echo "This output was generated by the Step (EXAMPLE_STEP_OUTPUT): $EXAMPLE_STEP_OUTPUT"
-
+    - go-list:
+    - golint:
+    - errcheck:
+    - go-test:
+    after_run:
+    - run_test
 
   # ----------------------------------------------------------------
   # --- workflows to Share this step into a Step Library
@@ -58,6 +35,58 @@ workflows:
             #!/bin/bash
             set -ex
             stepman audit --step-yml ./step.yml
+  
+  run_test:
+    envs:
+    - GRADLE_TASK: assembleDebug
+    - APK_FILE_INCLUDE_FILTER: "*.apk"
+    after_run:
+    - create_apk
+
+  create_apk:
+    steps:
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -ex
+            rm -rf ./_tmp
+    - change-workdir:
+        title: Switch working dir to test/_tmp dir
+        run_if: true
+        inputs:
+        - path: ./_tmp
+        - is_create_path: true
+    - script:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            set -x
+            if [[ -z "${SAMPLE_APP_REPOSITORY_URL}" ]]; then
+              echo "error: there is no SAMPLE_APP_URL env var specified"
+              exit 1
+            elif [[ -z "${COMMIT}" && -z "${BRANCH}" ]]; then
+              echo "error: can't checkout: there is no BRANCH or COMMIT env var specified"
+              exit 1
+            fi
+            git init
+            git remote add origin "${SAMPLE_APP_REPOSITORY_URL}"
+            git fetch || exit 1
+            [[ -n "${COMMIT}" ]] && git checkout "${COMMIT}" || git checkout "${BRANCH}"
+    - install-missing-android-tools:
+        inputs:
+        - ndk_revision: '16'
+        run_if: ".IsCI"
+    - gradle-runner:
+        inputs:
+        - gradle_task: "$GRADLE_TASK"
+        - gradlew_path: "$GRADLEW_PATH"
+        - apk_file_include_filter: $APK_FILE_INCLUDE_FILTER
+    - path::./:
+        is_skippable: false
+        title: Test zipalign APK
+        inputs:
+        - bitrise_unaligned_apk_path: $BITRISE_APK_PATH
 
   share-this-step:
     envs:
